In [6]:
import numpy as np

In [2]:
import glob
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
%matplotlib inline

In [3]:
import PIL
from PIL import Image

In [4]:
image = Image.open('./training_images/bB/horsey.png').convert("L")
image.show()

In [8]:
image_data = np.asarray(image)
print(image_data.shape)
print(image_data)

(100, 100)
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
